In [40]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sentence_transformers import SentenceTransformer
import torch

In [41]:
train_dataset = pd.read_csv("C:/Users/sevinj.rahimova/Desktop/Kaggle competition/RSNA Knee Abnormality Detection/Data/train.csv")

In [42]:
train_dataset.head()

,StudyInstanceUID,Report,ACL,MCL,Medial Meniscus,Lateral Meniscus,Medial OA,Lateral OA,PF OA,Effusion,Synovitis,Baker's,Contusion,Fracture
0,1.2.826.0.1.3680043.8.498.10004873229099053869...,Técnica: RMN de la rodilla. Resultados: Rotura...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1.2.826.0.1.3680043.8.498.10004945927472656027...,[DATE]: * MR Knie Rechts 15ch AA Klinische Inl...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1.2.826.0.1.3680043.8.498.10009278692606631573...,Hallazgos:\nNo hay alteraciones en significati...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1.2.826.0.1.3680043.8.498.10009639203170750274...,"In the medial compartment, the meniscus is no...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1.2.826.0.1.3680043.8.498.10013663742400736029...,CONSTATATIONS :\n\nFractures :\nAucune.\n\nAli...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [43]:
def basic_eda(train_dataset):
   
    print("--- Dataset Shape (Rows, Columns) ---")
    print(train_dataset.shape, "\n")
    
    print("--- Data Types & Non-Null Counts ---")
    print(train_dataset.info(), "\n")
    print(" ")
    print("--- Missing Values Count ---")
    print(train_dataset.isnull().sum(), "\n")
    print(" ")
    print("--- Duplicate Rows Count ---")
    print(f"Duplicates: {train_dataset.duplicated().sum()}\n")
    print(" ")
    print("--- Descriptive Statistics (Numeric) ---")
    print(train_dataset.describe(), "\n")
    print(" ")
    print("--- Descriptive Statistics (Categorical) ---")
    print(train_dataset.describe(include=['O']), "\n")


basic_eda(train_dataset)

--- Dataset Shape (Rows, Columns) ---
(4407, 14)

--- Data Types & Non-Null Counts ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4407 entries, 0 to 4406
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   StudyInstanceUID  4407 non-null   object
 1   Report            4407 non-null   object
 2   ACL               58 non-null     float64
 3   MCL               58 non-null     float64
 4   Medial Meniscus   58 non-null     float64
 5   Lateral Meniscus  58 non-null     float64
 6   Medial OA         58 non-null     float64
 7   Lateral OA        58 non-null     float64
 8   PF OA             58 non-null     float64
 9   Effusion          58 non-null     float64
 10  Synovitis         58 non-null     float64
 11  Baker's           58 non-null     float64
 12  Contusion         58 non-null     float64
 13  Fracture          58 non-null     float64
dtypes: float64(12), object(2)
memory usage: 482.1+ KB
None


--- Missing Values Count ---
StudyInstanceUID       0
Report                 0
ACL                 4349
MCL                 4349
Medial Meniscus     4349
Lateral Meniscus    4349
Medial OA           4349
Lateral OA          4349
PF OA               4349
Effusion            4349
Synovitis           4349
Baker's             4349
Contusion           4349
Fracture            4349
dtype: int64


--- Duplicate Rows Count ---
Duplicates: 0


--- Descriptive Statistics (Numeric) ---
             ACL        MCL  Medial Meniscus  Lateral Meniscus  Medial OA  \
count  58.000000  58.000000        58.000000         58.000000  58.000000
mean    0.413793   0.155172         0.448276          0.396552   0.258621
std     0.496814   0.365231         0.501661          0.493454   0.441701
min     0.000000   0.000000         0.000000          0.000000   0.000000
25%     0.000000   0.000000         0.000000          0.000000   0.000000
50%     0.000000   0.000000         0.000000          0.000000   0.000000
75%     1.000000   0.000000         1.000000          1.000000   0.750000
max     1.000000   1.000000         1.000000          1.000000   1.000000

       Lateral OA      PF OA   Effusion  Synovitis    Baker's  Contusion  \
count   58.000000  58.000000  58.000000  58.000000  58.000000  58.000000
mean     0.189655   0.362069   0.603448   0.465517   0.206897   0.327586
std      0.395452   0.484796   0.493454   0.503166   0.408619   0.473432
min      0.000000   0.000000   0.000000   0.000000   0.000000   0.000000
25%      0.000000   0.000000   0.000000   0.000000   0.000000   0.000000
50%      0.000000   0.000000   1.000000   0.000000   0.000000   0.000000
75%      0.000000   1.000000   1.000000   1.000000   0.000000   1.000000
max      1.000000   1.000000   1.000000   1.000000   1.000000   1.000000

        Fracture
count  58.000000
mean    0.310345
std     0.466675
min     0.000000
25%     0.000000
50%     0.000000
75%     1.000000
max     1.000000


--- Descriptive Statistics (Categorical) ---
                                         StudyInstanceUID  \
count                                                4407
unique                                               4407
top     1.2.826.0.1.3680043.8.498.10004873229099053869...
freq                                                    1

                                                   Report
count                                                4407
unique                                               4276
top     Diz eklemi içi sıvı miktarı normal. Çapraz ve ...
freq                                                   37

In [44]:
train_dataset.nunique()

StudyInstanceUID    4407
Report              4276
ACL                    2
MCL                    2
Medial Meniscus        2
Lateral Meniscus       2
Medial OA              2
Lateral OA             2
PF OA                  2
Effusion               2
Synovitis              2
Baker's                2
Contusion              2
Fracture               2
dtype: int64

In [45]:
train_dataset["ACL"].unique()

array([nan,  0.,  1.])

In [46]:
# Label distribution: Positive (1), Negative (0), Missing (NaN)

label_columns = [
    'ACL',
    'MCL',
    'Medial Meniscus',
    'Lateral Meniscus',
    'Medial OA',
    'Lateral OA',
    'PF OA',
    'Effusion',
    'Synovitis',
    "Baker's",
    'Contusion',
    'Fracture'
]

distribution = pd.DataFrame({
    'Positive (1)': [train_dataset[col].eq(1).sum() for col in label_columns],
    'Negative (0)': [train_dataset[col].eq(0).sum() for col in label_columns],
    'Missing (NaN)': [train_dataset[col].isna().sum() for col in label_columns]
}, index=label_columns)

print(distribution)

                  Positive (1)  Negative (0)  Missing (NaN)
ACL                         24            34           4349
MCL                          9            49           4349
Medial Meniscus             26            32           4349
Lateral Meniscus            23            35           4349
Medial OA                   15            43           4349
Lateral OA                  11            47           4349
PF OA                       21            37           4349
Effusion                    35            23           4349
Synovitis                   27            31           4349
Baker's                     12            46           4349
Contusion                   19            39           4349
Fracture                    18            40           4349

In [47]:
imbalance_table = pd.DataFrame({
    'Positive': [train_dataset[col].eq(1).sum() for col in label_columns],
    'Negative': [train_dataset[col].eq(0).sum() for col in label_columns]
}, index=label_columns)

imbalance_table['Positive %'] = (
    imbalance_table['Positive'] /
    (imbalance_table['Positive'] + imbalance_table['Negative'])
) * 100

imbalance_table['Negative %'] = (
    imbalance_table['Negative'] /
    (imbalance_table['Positive'] + imbalance_table['Negative'])
) * 100

imbalance_table['Imbalance Ratio'] = (
    imbalance_table['Negative'] /
    imbalance_table['Positive']
)

imbalance_table = imbalance_table.sort_values(
    'Imbalance Ratio',
    ascending=False
)

print(imbalance_table.round(2))

                  Positive  Negative  Positive %  Negative %  Imbalance Ratio
MCL                      9        49       15.52       84.48             5.44
Lateral OA              11        47       18.97       81.03             4.27
Baker's                 12        46       20.69       79.31             3.83
Medial OA               15        43       25.86       74.14             2.87
Fracture                18        40       31.03       68.97             2.22
Contusion               19        39       32.76       67.24             2.05
PF OA                   21        37       36.21       63.79             1.76
Lateral Meniscus        23        35       39.66       60.34             1.52
ACL                     24        34       41.38       58.62             1.42
Medial Meniscus         26        32       44.83       55.17             1.23
Synovitis               27        31       46.55       53.45             1.15
Effusion                35        23       60.34       39.66             0.66

In [73]:

from sklearn.metrics import (
    confusion_matrix,
    accuracy_score,
    precision_score,
    recall_score,
    f1_score
)

# Yalnız label-i məlum olan MCL nümunələri
y_true = train_dataset['MCL'].dropna().astype(int)

# Sadə baseline:
# model bütün xəstələrə "negative" (0) deyir
y_pred = np.zeros(len(y_true), dtype=int)

In [74]:
print("y_true:", y_true.shape)
print("y_pred:", y_pred.shape)

y_true: (58,)
y_pred: (58,)

In [50]:
cm = confusion_matrix(y_true, y_pred)

print(cm)

[[49  0]
 [ 9  0]]

In [51]:
accuracy = accuracy_score(y_true, y_pred)

precision = precision_score(
    y_true,
    y_pred,
    zero_division=0
)

recall = recall_score(
    y_true,
    y_pred,
    zero_division=0
)

f1 = f1_score(
    y_true,
    y_pred,
    zero_division=0
)

print(f"Accuracy : {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall   : {recall:.4f}")
print(f"F1 Score : {f1:.4f}")

Accuracy : 0.8448
Precision: 0.0000
Recall   : 0.0000
F1 Score : 0.0000

In [52]:
df_mcl = train_dataset[
    train_dataset['MCL'].notna()
][['Report', 'MCL']].copy()

df_mcl['MCL'] = df_mcl['MCL'].astype(int)

print(df_mcl.shape)
print(df_mcl['MCL'].value_counts())

(58, 2)
MCL
0    49
1     9
Name: count, dtype: int64

In [53]:
from sklearn.model_selection import train_test_split

X = df_mcl['Report']
y = df_mcl['MCL']

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("Train:", X_train.shape)
print("Test :", X_test.shape)

print("\nTrain distribution:")
print(y_train.value_counts())

print("\nTest distribution:")
print(y_test.value_counts())

Train: (46,)
Test : (12,)

Train distribution:
MCL
0    39
1     7
Name: count, dtype: int64

Test distribution:
MCL
0    10
1     2
Name: count, dtype: int64

In [54]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(
    max_features=5000,
    ngram_range=(1, 2)
)

X_train_tfidf = tfidf.fit_transform(X_train)
X_test_tfidf = tfidf.transform(X_test)

print("Train TF-IDF shape:", X_train_tfidf.shape)
print("Test TF-IDF shape :", X_test_tfidf.shape)

Train TF-IDF shape: (46, 5000)
Test TF-IDF shape : (12, 5000)

In [55]:
tfidf.fit_transform(X_train)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 8837 stored elements and shape (46, 5000)>

In [56]:
tfidf.transform(X_test)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 2155 stored elements and shape (12, 5000)>

In [57]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(
    random_state=42
)

model.fit(X_train_tfidf, y_train)

LogisticRegression(random_state=42)

In [58]:
y_pred = model.predict(X_test_tfidf)

In [59]:
y_prob = model.predict_proba(X_test_tfidf)[:, 1]

In [60]:
print(y_pred)

[0 0 0 0 0 0 0 0 0 0 0 0]

In [61]:
print(y_prob)

[0.1246718  0.13522934 0.15492451 0.11223931 0.1552786  0.16823008
 0.13681901 0.19728761 0.14863558 0.14145638 0.17869751 0.14430204]

In [62]:
results = pd.DataFrame({
    'Actual': y_test.values,
    'Probability': y_prob
})

results = results.sort_values(
    'Probability',
    ascending=False
)

print(results)

    Actual  Probability
7        0     0.197288
10       0     0.178698
5        0     0.168230
4        0     0.155279
2        0     0.154925
8        1     0.148636
11       0     0.144302
9        0     0.141456
6        1     0.136819
1        0     0.135229
0        0     0.124672
3        0     0.112239

In [63]:
model_balanced = LogisticRegression(
    class_weight='balanced',
    random_state=42
)

model_balanced.fit(X_train_tfidf, y_train)

y_prob_balanced = model_balanced.predict_proba(
    X_test_tfidf
)[:, 1]

y_pred_balanced = (
    y_prob_balanced >= 0.5
).astype(int)

In [64]:
from sklearn.metrics import classification_report

print(classification_report(
    y_test,
    y_pred_balanced,
    zero_division=0
))

              precision    recall  f1-score   support

           0       0.82      0.90      0.86        10
           1       0.00      0.00      0.00         2

    accuracy                           0.75        12
   macro avg       0.41      0.45      0.43        12
weighted avg       0.68      0.75      0.71        12

In [65]:
for threshold in [0.5, 0.4, 0.3, 0.2, 0.1]:
    
    y_pred_threshold = (
        y_prob_balanced >= threshold
    ).astype(int)
    
    print(f"\nThreshold = {threshold}")
    
    print(classification_report(
        y_test,
        y_pred_threshold,
        zero_division=0
    ))

Threshold = 0.5
              precision    recall  f1-score   support

           0       0.82      0.90      0.86        10
           1       0.00      0.00      0.00         2

    accuracy                           0.75        12
   macro avg       0.41      0.45      0.43        12
weighted avg       0.68      0.75      0.71        12


Threshold = 0.4
              precision    recall  f1-score   support

           0       0.83      0.50      0.62        10
           1       0.17      0.50      0.25         2

    accuracy                           0.50        12
   macro avg       0.50      0.50      0.44        12
weighted avg       0.72      0.50      0.56        12


Threshold = 0.3
              precision    recall  f1-score   support

           0       1.00      0.10      0.18        10
           1       0.18      1.00      0.31         2

    accuracy                           0.25        12
   macro avg       0.59      0.55      0.24        12
weighted avg       0.86      0.25      0.20        12


Threshold = 0.2
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        10
           1       0.17      1.00      0.29         2

    accuracy                           0.17        12
   macro avg       0.08      0.50      0.14        12
weighted avg       0.03      0.17      0.05        12


Threshold = 0.1
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        10
           1       0.17      1.00      0.29         2

    accuracy                           0.17        12
   macro avg       0.08      0.50      0.14        12
weighted avg       0.03      0.17      0.05        12

-------------------------

In [66]:
train_dataset['Report'].sample(20, random_state=42).tolist()

['Regelrechte Stellungsverhältnisse im Kniegelenk. Allseits regelrechtes Knochenmarksignal. Kein Hinweis auf eine Fraktur oder ein Bone-bruise. Stigmata der medial betonten Gonarthrose mit Gelenkspaltverschmälerung und osteophytären Randausziehungen sowie Chondropathie femorotibial bds. Keine höhergradige Chondropathie femoropatellar. Vorderes und hinteres Kreuzband sowie LCL intakt. Quadrizeps- und Patellarsehne intakt ohne Signalalteration. Der Innenmeniskus mukoide mit horizontaler Rissbildung. Auch der Außenmeniskus mukoid verändert ohne Nachweis einer Rissbildung. Fibroostosen der Quadrizepssehne. Geringer Gelenkerguss. Unauffällige Darstellung der Weichteile.',
 'SAĞ DİZ MRG. Tetkik protokolü: Çok düzlemli, çok sekanslı. Bulgular: Medial meniscüs posterior hornunda grade II dejenerasyon ve ayrıca horizontal yırtık ile uyumlu görünüm mevcuttur. Medial menisküs posterior horn komşuluğunda 7x6 mm boyutlarında ince septalı parameniskal kist izlendi.Lateral menisküste anterior horn grade II dejenerasyon izlenmiştir.Ön çaprazda sinyal artışı mevcuttur. Arka çapraz bağ, lateral ve medial kollateral ligaman normaldir.Medial kollateral ligamen çevresinde sıvı artışı izlendi  ( grade I sprain ).Distal kuadriseps  normaldir. Patella normal yerleşimlidir. Retinaküler devamsızlık yoktur.Suprapatellar bursada ve diz ekleminde sıvı artışı izlendi. Tibia medial plato seviyesinde kemik iliği ödemi izlendi.Patellar tendonda sinyal artışı izlendi.',
 'Prikazane koštane strukture primjerenih intenziteta signala i morfologije.\nPrikazana zglobna tijela primjereno su uzglobljena.\nPrikaže se hondromalacija III° trohleje femura te hondromalacija III° obje fasete patele, uz\nreduciranu debljinu hrskavica i formirane manje rubne osteofite - u smislu degenerativnih\npromjena.\nBlago reducirana debljina hrskavice medijalnog tibijalnog platoa uz hondromalaciju II° uz rubno\nformirane manje osteofite - u smislu degenerativnih promjena.\nHondromalacija II° hrskavice lateralnog tibijalnog platoa te formirane rubne osteofite - u smislu\ndegenerativnih promjena.\nKompleksna ruptura trupa, stražnjeg roga i stražnjeg korijena medijalnog meniska uz ekstruziju\nmeniska za oko 2 mm. Degeneratino promijenjen, stanjen medijalni menisk.\nPromijenjen intenzitet signala lateralnog meniska u sklopu degenerativnih promjena, u stražnjem\nrogu vidljiva manja longitudinalna ruptura s tibijalne strane.\nPotpuna ruptura prednjeg križnog ligamenta.\nStražnji križni ligament je primjerenih intenziteta signala i održanog kontinuiteta, uz tibijalno\nhvatište nalazi se nekoliko sitnih intraosealnih ganglion cisti promjera do 3 mm.\nMedijalni i lateralni kolateralni ligament su primjerenih intenziteta signala, održanog kontinuiteta.\nUredan prikaz tetive popliteusa, iliotibijalnog trakta i pes anserinus.\nBlaže promijenjen intenzitet signala tetive kvadricepsa i patelarnog ligamenta na hvatištima za\npatelu, održanog kontinuiteta - odgovara entezopatiji.\nPatelarni retinakulumi održani.\nBez signifikantnog izljeva u zglob.\nPotkožni edem infrapatelarno.\nNe nalazi se znakova poplitealne ciste.',
 'ΤΕΧΝΙΚΗ: Η εξέταση έγινε σε Τοµογράφο 3Τ µε ακολουθίες παλµών pd/T2 fsκαι Τ1. ΕΥΡΗΜΑΤΑ: - Παρατηρείται σύµπλοκη εκφυλιστική ρήξη στο οπίσθιο κέρας του έσω µηνίκσου. - Αναγνωρίζεται επίσης πλήρης διακοπή των ινών του πρόσθιου χιαστού συνδέσµου, ως επί πλήρης ρήξης του. - Φυσιολογική είναι η απεικόνιση του οπίσθιου χιαστού και των πλαγίων συνδέσµων, του αρθρικού χόνδρου καθώς και του έξω µηνίσκου. - Εικόνα ύδραρθρου µε αιµορραγικά στοιχεία σε φάση απορρόφησης. - Από τον έλεγχο του οστικού µυελού παρατηρείται περιοχή οστεοµυελικού οιδήµατος στην εγγύς επίφυση και µετάφυση της κνήµης, κυρίως οπισθίως. Συνυπάρχει προβολή του ερυθρού στοιχείου, που αποδίδεται σε καλοήθη υπερπλασία. - Χωρίς παθολογικά ευρήµατα από τον έλεγχο του εκτατικού µηχανισµού.',
 'MRI of right knee in sagittal section (Proton density with fat saturation, T1WI, T2WI with fat saturation), axial section (T2WI with fat saturation) and coronal section (T2WI with fat saturation):\n\n* Mild blurred contour of posterior cruciate ligament (PCL) with increased signal intensity is noticed, in favor of PCL tear.\n\n* Fluid accumulation in the suprapatellar bursa with plica inside is noticed, indicating suprapatellar bursitis.\n\n> The contour of anterior cruciate ligament (ACL) appears to be within normal, no abnormal signal intensity is noted.\n> No evidence of tear is noted in either medial or lateral meniscus.\n> Both medial & lateral collateral ligaments appear to be within normal.\n> No evidence of bone contusion is noted.\n\nImpressions: \n1. In favor of PCL tear\n2. Suprapatellar bursitis of right knee\n\nSuggest clinical correlation\n           \n\n\n                     ',
 'Medijalna subluksacija femorotibijalnog zgloba. Osteofiti rubno femorotibijalno. Koštani edem\nlateralnog epikondila femura i tibije u duljini od 9mm u smislu hondromalacije tip IV. Manji koštani\nedemi subhondralno medijalnog kondila femura i tibije u duljini od 4 mm u smislu hondromalacije\ntip IV sa potpunim gubitkom normalne debljine hrskavice. Blagi koštani edem na hvatištu\nstražnjeg križnog ligamenta.\nOpsežno izljeva u zglobu, u suprapatelarnom te medijalnom i lateralnom recesusu.\nPovišenje inteziteta signala prednjeg križnog ligamenta u smislu parcijalne rupture.\nZadebljan stražnji križni ligament koji se prati u kontinuitetu - degenerativne promjene.\nKompleksna ruptura prednjeg roga i trupa lateralnog meniska na bazi degenerativnih promjena.\nDegeneracija stražnjeg roga lateralnog meniska.\nKompleksna ruptura medijalnog meniska.\nSinovijalne ciste uz dorzalni tibijalni kondil veličine 26x26x13mm.\nIzljev uz medijalni kolateralni ligament koji je zadebljan u proksimalnoj trećini te održanog\nkontinuiteta, prvenstveno degenerativne promjene.\nLateralni kolateralni ligamenti urednog signala te se prate u kontinuitetu.\nUredan je intenzitet signala hvatišta tetive kvadricepsa i patelarnog ligamenta.\nBaker cista veličine 53x34x26mm.\nUredna je kongruencija zglobnih tijela femoropatelarnog zgloba. Uredan intenzitet signala\npatelarne hrskavice. Edem Hoffa masnog jastučića.',
 "Exam Type: MRI KNEE RIGHT WO CONTRAST\nExam Date and Time: [DATE] [TIME]\nIndication: Chronic torn ACL. Right lateral knee pain after fall.\nComparison: No relevant prior studies available for comparison.\n\nTECHNIQUE:\nMRI of the right knee was performed on a 1.5 Tesla system with a dedicated knee coil in three planes (axial, sagittal, and coronal), using a standard non-contrast protocol.\n\nFINDINGS:\nOSSEOUS STRUCTURES:\nAlignment is anatomic. No acute fracture or bone bruise. Background marrow signal is normal without infiltrative marrow process. No aggressive osseous lesions.\n\nJOINT SPACE:\nSmall joint effusion. No intra-articular bodies. No Baker's cyst. T1 and T2 hypointense 3 cm lesion in the posterior joint capsule, along the posterior cruciate ligament.\n\nMEDIAL COMPARTMENT:\nMedial meniscus: Oblique undersurface tear of the posterior horn.\nMedial compartment cartilage: No focal cartilage defects.\n\nLATERAL COMPARTMENT:\nLateral meniscus: Complex tear of the body and posterior horn with a dominant horizontal component extending to the root attachment. Mild extrusion of the body.\nLateral compartment cartilage: Mild chondrosis with high-grade partial-thickness cartilage loss of the femoral condyle and tibial plateau.\n\nPATELLOFEMORAL COMPARTMENT:\nPatellofemoral compartment cartilage: Moderate chondrosis, with diffuse high-grade partial-thickness cartilage loss and areas of full-thickness fissuring in the medial patellar facet\n\nCRUCIATE LIGAMENTS:\nAnterior cruciate ligament (ACL): Chronic complete ACL tear.\nPosterior cruciate ligament (PCL): Normal.\n\nCOLLATERAL LIGAMENTS & POSTEROLATERAL CORNER:\nMedial collateral ligament (MCL): Normal.\nLateral collateral ligament (LCL) complex: Normal.\nPosterolateral corner structures: Normal.\n\nEXTENSOR MECHANISM:\nDistal quadriceps tendon: Mild distal quadriceps insertional tendinosis. No tendon tear.\nPatella tendon: No tendinosis or tear.\nMedial patellofemoral ligament (MPFL) and patellar retinacula: Normal.\nPatellofemoral tracking: No edema in superolateral Hoffa's fat pad. No lateral patellar tilt or translation. No patella alta. Normal patellar and trochlear morphology. Normal tibial tubercle-trochlear groove (TT-TG) distance measuring 13 mm.\n\nMUSCLES/TENDONS:\nNo acute muscle strain or muscle atrophy. Visualized tendons not previously discussed are intact without tendinosis or tear.\n\nSOFT TISSUES:\nNo soft tissue mass. Normal popliteal neurovascular bundle.\n\nIMPRESSION:\n1.\tOblique undersurface tear of the posterior horn of the medial meniscus.\n2.\tComplex tear of the lateral meniscus with a dominant horizontal component and mild extrusion of the body.\n3.\tMild lateral and moderate patellofemoral compartment chondrosis.\n4.\tChronic complete ACL tear.\n5.\t3 cm hypointense lesion in the posterior joint capsule, with features consistent with PVNS.",
 'Zentrierte Stellung im rechten Kniegelenk. Zentrierte Stellung der Patella. Keine trochleäre Dysplasie. Regelrechter Knorpelbelag retropatellar. Gering streifige hypointense Signalveränderungen des Knorpelbelages zentral in der Trochlea mit subchondral kleinzystischen Veränderungen und Ödemsignal, hier V.a. fokal osteochondrale Läsion (5/15, 4/19 + 6/20). Keine wesentliche Chondropathie femoro-tibial im medialen und lateralen Kompartiment oder retropatellar. Keine wesentliche Gelenkspaltverschmälerung. Kleine umschrieben T2-hyperintense Läsion in der Femurmetaphyse mit 7 mm (5/19, 4/14), morph. passend zu einem Enchondrom. Gering Gelenkerguss, keine freienn Gelenkkörper. Intaktes vorderes und hinteres Kreuzband. Intaktes mediales und laterales Kollateralband. Unauffällige Darstellung des medialen und lateralen Meniskus bezogen auf Formgebung und Signalintensität. Intakte Darstellung der Quadriceps- und Patellarsehne. Unauffällige Darstellung der umgebenden Muskulatur und Weichteile. ',
 'Diz eklemi içi sıvı miktarı normal. Ön çapraz bağın femoral insersiyonunda parsiyel yırtık izleniyor. Arka çapraz ve yan bağlar normal. Posterolateral ve posteromedyal köşe yapıları korunmuş. Medyal menisküs ve lateral menisküs normal. Tibyal platonun posterolateralinde kontüzyonel hafif kemik iliği ödemi izleniyor. Eklem kıkırdakları ve kemikler diğer keismlerde normal. Ekstensör mekanizma korunmuş. Femoral troklear displazik (Dejour tip B). Patella laterale 9 mm translasyon gösteriyor. Patella yüksek yerleşimli (Caton-Deschamps indeksi 1.48) . Gastrokinemius-semimembranöz bursasındaki en çok 5 cm boyutlu sıvı lokülasyonu sızdırmıyor.',
 'Exam Type: MRI KNEE RIGHT WO CONTRAST\nExam Date and Time: [DATE] [TIME]\nIndication: Right knee buckling. Osteoarthritis. ACL sprain. Medial meniscus tear. \nComparison: [REDACTED]. \n\nTECHNIQUE:  Multiplanar and multisequence MRI of the right  knee without IV contrast.   \n\nFINDINGS: \n\nJOINT EFFUSION:  Small joint effusion. Small leaking popliteal cyst. \n\nANTERIOR CRUCIATE LIGAMENT:  Intact. \n\nPOSTERIOR CRUCIATE LIGAMENT:  Intact. \n\nMEDIAL MENISCUS: Large horizontal undersurface tear of the body and posterior horn of the medial meniscus. There is also low-grade tearing of the posterior root attachment. Mild peripheral meniscal extrusion. \n\nMEDIAL COMPARTMENT:  Subchondral fracture line is noted along the weightbearing segment of the medial femoral condyle, with probable nondisplaced osteochondral lesion. This measures 15 mm AP and 10 mm transverse. Moderate degree of associated bone marrow edema.\n\nThere is also mild medial compartment osteoarthritis, with subchondral cystic changes of the tibial plateau. \n\nLATERAL MENISCUS:  Intact.\n\nLATERAL COMPARTMENT:  Within normal limits. \n\nMEDIAL COLLATERAL LIGAMENT:  Edema along the medial collateral ligament suggestive of grade 1 sprain pattern. No discrete tear. \n\nLATERAL COLLATERAL LIGAMENT COMPLEX:  Intact.\n\nPATELLOFEMORAL COMPARTMENT: Low-grade fissuring of the patellar cartilage. No high-grade or full-thickness cartilage defect. No subchondral edema. \n\nEXTENSOR APPARATUS:  Superior and inferior patellar enthesophytes. Small interstitial tear in the proximal patellar tendon. \n\nBONE MARROW:  As above. \n \nOTHER:  None. \n\n\nIMPRESSION:\n\n1. Large horizontal undersurface tear of the body and posterior horn of the medial meniscus. Mild peripheral meniscal extrusion.\n\n2. Subchondral fracture line of the medial femoral condyle, likely in the context of nondisplaced osteochondral lesion.\n\n3. Mild medial compartment osteoarthritis.\n\n4. Grade 1 sprain pattern of the medial collateral ligament. Intact cruciate ligaments.\n\n5. Small knee joint effusion and leaking popliteal cyst. \n\n\nSigned By: [NAME] \n Signed On: [DATE]',
 'Técnica: RMN de la rodilla. Resultados: Rotura de menisco interno. Edema de médula ósea subcondral en la meseta tibial medial y edema de tejidos blandos adyacentes. Quiste de Baker. Derrame. Impresión: Rotura de menisco interno. Edema de médula ósea subcondral en la meseta tibial medial y edema de tejidos blandos adyacentes. Quiste de Baker. Derrame.',
 'МР находка: Няма данни за ставен излив. Костите, формиращи колянната става са с нормална форма и структура. Няма данни за костномозъчен едем. Ставният хрущял е съхранен. МР данни за мукоидна дегенерация на предната кръстна връзка. Връзката се проследява по цялото и протежение, но е с уголемен напречник и лекостепенно повишен интензитет на сигнала. Задната кръстна връзка е интактна. Колатерални лигаменти – без особености. Ретинакулуми – б.о. МР данни за дегенеративна промяна в задния рог на медиалния менискус. Задният рог на медиалния менискус е с повишен сигнален интензитет. Дорзомедиално от менискуса, в непосредствена близост до него се визуализира кистична лезия с размери 12/8/7мм. Кистата е с висок сигнален интензитет при Т2 сериите и нисък в Т1. В тази киста се вижда единично септиране. Нормално представен е латералният менискус. Сухожилие на м. квадрицепс феморис, лигамент на пателата – нормално изобразяване. Поплитеална ямка – б.о. Заключение:\nМР данни за дегенеративна промяна в задния рог на медиалния менискус със съмнение за менискална киста, свързана с него. Мукоидна дегенерация на предна кръстна връзка. ',
 '[DATE]: MR Knie Rechts 15ch AA: Klinische inlichtingen: Zie gescande aanvraag Diagnostische vraagstelling: Zie gescande aanvraag Bevindingen: Kleine artrosynoviale cyste gelegen anterieur van het lateraal femorotibiaal compartiment, met afmetingen 17 x 9 x 7\\~mm polylobulair, wellicht op basis van degeneratieve scheur van de voorste hoorn van de meniscus. Minimaal gewrichtsvocht. Normaal voorkomen patellapees en quadricepspees. Normaal voorkomen kruisbanden en laterale banden. Degeneratieve scheur posterieure hoorn mediale meniscus met uitloper in de ondervlakte , uitbreidend naar het corpus met verplaatst fragment in de inferieure meniscale recessus met bijhorend oedeem van boord van het mediale tibiaplateau, reactioneel. Muco ïde cyste onder de insertie van de posterieure kruisband, banaal. Besluit: - Degeneratieve scheur voorste hoorn laterale meniscus met kleine parameniscale cyste. - Meer uitgebreide degeneratieve scheur posterieure hoorn mediale meniscus met uitbreiding naar corpus met verplaatst meniscaal fragment in de inferieure meniscale recessus met bijhorend oedeem op de mediale boord van het mediale tibiaplateau.',
 'Uredan intenzitet signala koštanih struktura.\nHondromalacija II. stupnja femoralne i tibijalne hrskavice.\nMinimalna količina izljeva u FT i FP zglobu.\nKrižni ligamenti su urednih intenziteta signala, prate se u kontinuitetu.\nMedijalni menisk pokazuje znakove degeneracije bez sigurnih znakova rupture. Lateralni menisk\nurednog intenziteta signala.\nLateralni i medijalni kolateralni ligamenti urednog signala te se prate u kontinuitetu.\nUredan intenzitet signala hvatišta tetive kvadricepsa i patelarnog ligamenta.\nBez znakova poplitealne ciste.\nUredna je kongruencija zglobnih tijela femoropatelarnog zgloba. U podrucju lateralnog dijela\npatele linearna zona povisenog inteziteta signala moze odgovarati i stanju nakon traume.\nHondromalacija I. stupnja patelarne hrskavice.',
 'МР находка: МР данни за лезия на задния рог на медиалния менискус. В него се вижда хиперинтензна линия с кос ход, съответстваща на скъсване. Скъсването достига до задния край на менискуса и видимо не достига до ставните повърхности на фемура и тибията. Няма данни за формиран фрагмент. Нормално изобразяване на предния рог на медиалния менискус и на латералния менискус. Ставният хрущял на фемура, тибията и пателата е интактен. Нормално изобразяване на кръстните връзки. Колатерални лигаменти – б.о. Костите, формиращи дясната колянна става, са с нормална форма и сигнален интензитет. Патела, ретинакулуми на пателата – б.о. Сухожилие на m. quadriceps femoris, лигамент на patella – нормално изобразяване. Наличие на минимален ставен излив. Не се изобразяват промени в меките тъкани на дясното коляно. Заключение: МР данни за скъсване в задния рог на медиалния менискус – grade 2а. Минимален ставен излив. ',
 'Centralno u distalnom femuru, tibiji i glavi fibule vide se mrljaste zone crvene rekonverzije\nkoštane srži.\nHondromalacija IV. stupnja obje patelarne fasete s priležećim manjim zonama koštanog edema.\nHondromalacija IV. stupnja medijalnog kompartmenta TF zgloba - početne OA promjene.\nMinimalan izljev suprapatelarno i intraartikularno.\nPrednji križni ligament blaže do umjereno deg. promijenjen te se prati u kontinuitetu.\nStražnji križni ligament urednog signala te se prati u kontinuitetu.\nMedijalni menisk bez znakova degeneracije ili rupture.\nLateralni menisk bez znakova degeneracije ili rupture.\nLateralni i medijalni kolateralni ligamenti urednog signala te se prate u kontinuitetu.\nUredan intenzitet signala hvatišta tetive kvadricepsa i patelarnog ligamenta.\nBez znakova poplitealne ciste.\nUredna je kongruencija zglobnih tijela femoropatelarnog zgloba.',

In [67]:
acl_data = train_dataset[
    train_dataset['ACL'].notna()
][['Report', 'ACL']].copy()

acl_data['ACL'] = acl_data['ACL'].astype(int)

In [68]:
for _, row in acl_data.iterrows():
    print("=" * 100)
    print("LABEL:", row["ACL"])
    print(row["Report"])

====================================================================================================
LABEL: 0
Antecedentes Clínicos:
Esguince rodilla. [DATE].
Hallazgos:
No hay alteraciones de señal significativas de la médula ósea.
Ligamentos cruzados y colaterales dentro de límites normales.
Amputación marginal del cuerpo del menisco lateral. Menisco medial de morfología y señal
conservada, sin signos de rotura.
Cartílagos de los compartimentos femorotibiales sin alteraciones.
Fina úlcera condral focal de espesor total del aspecto inferior de la vertiente medial de la tróclea
femoral con mínimos cambios óseos secundarios. Fenómenos condrales reparativos de la región
central de la simple femoral. Cartílago rotuliano sin alteraciones.
Leve derrame articular. No hay quistes poplíteos patológicos.
Aumento de señal de la inserción distal del tendón cuadricipital y de la inserción proximal del
tendón rotuliano, sin signos de rotura.
No hay alteraciones de señal de la grasa de Hoffa.
Impresión:
Amputación marginal del cuerpo del menisco lateral.
Condropatía focal grado 4 del aspecto inferior de la vertiente medial de la tróclea femoral .
Fenómenos condrales reparativos de la región central de la tróclea femoral.
Leve derrame articular.
Leve tendinosis cuadricipital distal y rotuliana proximal.
====================================================================================================
LABEL: 0
 The study reveals normal knee joint alignment.   No fracture is seen.
   ACL is intact.   PCL is preserved.
  The MCL is intact.    Medial meniscus is not torn.
  The FCL, popliteus and biceps femoris tendons are preserved.
   Horizontal tear at anterior horn of the lateral meniscus is noted.
   Focal osteochondral defect at lateral patellar facet, about 8x12mm. with subchondral bone edema is detected.   Full thickness cartilage defect, 1.2x1.5cm. at lateral trochlea with subchondral bone edema is noted.   Small osteochondral body, about intact9xintact4cm. at anterior infrapatellar recess is noted.
  The quadriceps and patellar tendons are preserved.
   Moderate joint effusion, distended suprapatellar bursa with thickend synovial tissue are observed.  Horizontal tear at anterior horn of the lateral meniscus.
     Osteochondral fracture at lateral patellar facet, about 8x12mm. with dislodge OCD fragment.
     Full thickness cartilage defect, 1.2x1.5cm. at lateral trochlea with subchondral bone edema.
      Small osteochondral body, about intact9xintact4cm. at anterior infrapatellar recess.
      Chronic reactive synovitis, suprapatellar bursitis
====================================================================================================
LABEL: 0
Exam Type: MRI KNEE RIGHT WO CONTRAST
Exam Date and Time: [DATE] [TIME]
Indication: 2 years of pain with walking up and down the stairs twisting and squatting.
Comparison: No relevant prior studies available for comparison.

TECHNIQUE:
MRI of the right knee was performed on a 1.5 Tesla system body coil in three planes (axial, sagittal, and coronal), using a standard non-contrast protocol.

FINDINGS:
OSSEOUS STRUCTURES:
Alignment is anatomic. No acute fracture or bone bruise. Background marrow signal is normal without infiltrative marrow process. No aggressive osseous lesions. Tricompartmental marginal osteophytes

JOINT SPACE:
Small joint effusion. No intra-articular bodies. No Baker's cyst.

MEDIAL COMPARTMENT:
Medial meniscus: Extensive complete tearing of the body, posterior horn, and posterior root medial meniscus with severe extrusion.
Medial compartment cartilage: Full thickness cartilage loss along the medial femoral condyle and medial tibial plateau with subchondral cystic change and marrow edema.

LATERAL COMPARTMENT:
Lateral meniscus: Degenerative signal throughout the lateral meniscus without surfacing tear.
Lateral compartment cartilage: Mild cartilage heterogeneity and fissuring.

PATELLOFEMORAL COMPARTMENT:
Patellofemoral compartment cartilage: High-grade cartilage loss along the medial patellar facet. High grade cartilage loss at lateral trochlea.

CRUCIATE LIGAMENTS:
Anterior cruciate ligament (ACL): Normal with both bundles intact.
Posterior cruciate ligament (PCL): Normal.

COLLATERAL LIGAMENTS & POSTEROLATERAL CORNER:
Medial collateral ligament (MCL): Normal.
Lateral collateral ligament (LCL) complex: Normal.
Posterolateral corner structures: Normal.

EXTENSOR MECHANISM:
Distal quadriceps tendon: No tendinosis or tear.
Patella tendon: No tendinosis or tear.
Medial patellofemoral ligament (MPFL) and patellar retinacula: Normal.
Patellofemoral tracking: No edema in superolateral Hoffa's fat pad. No lateral patellar tilt or translation. No patella alta. Normal patellar and trochlear morphology. Normal tibial tubercle-trochlear groove (TT-TG) distance measuring 17 mm.

MUSCLES/TENDONS:
No acute muscle strain or muscle atrophy. Visualized tendons not previously discussed are intact without tendinosis or tear.

SOFT TISSUES:
Nonspecific prepatellar and scattered subcutaneous edema about the knee. No soft tissue mass. Normal popliteal neurovascular bundle.

IMPRESSION:
1.	Extensive complete tearing of the body, posterior horn, and posterior root medial meniscus with severe extrusion.
2.	Tricompartmental osteoarthritis worse in the medial compartment.
====================================================================================================
LABEL: 0
MRI of left Knee with
-3-Plane Loc R'T, Sag PD FS, AX T2 FS, Sag T2 FS, Sag T1, CORT2 FS

> There is no abnormal intensity or articular surface disrupt in the medial meniscus, It appears to be normal.
> There is no increased intensity in the ACL, MCL and LCL, it appears to be normal
> Interstitial high intensity, irregular contour and laxity in the PCL, suspected complete tear
> Synovial membrane thickening in the knee joint with fluid accumulation and hofa fat pad stranding, knee arthritis with hoffitis noted
> Fluid accumulated in the suprapatella bursa with quadricep and prefemoral fat pad stranding, suprapatellar bursitis noted
> Fluid accumulated in the posterior medial condyle region
> Medial plica and suprapatellar plicae noted
> Relatively enlarged caliber of the popliteal vein  with heterogenous hyperintensity (srs: 6, Img: 24-30) and prominenet superficial veines, the possiblity of deep vein thrombosis can't totally excluded.

Impression:
1. C/W PCL complete tear, grade 3 injury
2. Synovitis of left knee and massive joint effusion and suprapatellar bursitis; complex plicae.
3. Subcutaneous edema around left knee.
4. R/O deep vein thrombosis of left popliteal vein. Suggest correlation with clinical manifestation
Suggest correlation with clinical manifestation

====================================================================================================
LABEL: 1
 In the medial compartment, there is longitudinal vertical tear at the body and posterior horn of the medial meniscus. There is no focal chondrosis or chondral injury.
 The lateral compartment, the meniscus is not torn and there is no focal chondrosis or chondral injury.
 The patellofemoral joint, the patellar and trochlear cartilage appears congruent without chondral lesion. The medial patellofemoral ligament is intact.
 In the intercondylar notch, there is complete tear of the anterior cruciate ligament, at mid substance. The posterior cruciate ligament is intact. There is anterior tibial translation.
 The medial and lateral collateral ligament complexes are intact. The extensor mechanism is normal.
 No knee effusion is present. The surrounding musculature is normal. There is no fracture or bone contusion.   -- Longitudinal vertical tear at the body and posterior horn of the medial meniscus.
 -- Complete tear of the anterior cruciate ligament, at mid substance.
====================================================================================================
LABEL: 0
 In the medial compartment, the meniscus is not torn and there is no focal chondrosis or chondral injury.

 The lateral compartment, there is complex tear (main radial and longitudinal vertical component) at the posterior horn of the lateral meniscus. There is no focal chondrosis or chondral injury.

 The patellofemoral joint, the patellar and trochlear cartilage appears congruent without chondral lesion. The medial patellofemoral ligament is intact.
 In the intercondylar notch, there is interstitial tear of the anterior cruciate ligament, at mid substance. The posterior cruciate ligament is intact. There is no tibial translation.

 The medial collateral ligament complexes are intact. The posteromedial oblique ligament is intact.

 There is grade II ligamentous sprain (partial tear) of  lateral collateral ligament. Partial tear of the intraarticular portion, popliteus tendon is present. The popliteofibular ligament is intact. The meniscopopliteal fascicles are intact.

 The extensor mechanism is normal.

 Some amount of right knee effusion with hemarthrosis is present. There is popliteus muscle contusion.  There is no fracture or bone contusion.   Complex tear (main radial and longitudinal vertical component) at the posterior horn of the lateral meniscus.
  Interstitial tear of the anterior cruciate ligament, at mid substance.
  Grade II ligamentous sprain (partial tear) of  lateral collateral ligament.
  Partial tear of the intraarticular portion, popliteus tendon.
  Some amount of right knee effusion with hemarthrosis.
  Popliteus muscle contusion.
====================================================================================================
LABEL: 1
Antecedentes Clínicos:
Rodilla traumática aguda.
Hallazgos:
Rotura espesor y ancho total de la unión del tercio medio del tercio proximal del LCA asociado a
discreto edema óseo del aspecto posterior de platillo tibial lateral. LCP y ligamentos colaterales sin
alteraciones significativas.
Aumento de señal central del cuerno posterior y cuerpo del menisco medial que no impresiona
contactar con la superficie articular, sin caracteres propios de rotura.
Menisco lateral con pequeña rotura radial incompleta de la unión del cuerno posterior con el
cuerpo, sin desplazamiento de segmentos.
Úlcera condral de espesor total de la zona de carga del cóndilo femoral lateral que mide
aproximadamente 6 x 5 mm en sus ejes mediolateral y anteroposterior, sin cambios óseos
secundarios. Fina úlcera condral focal de espesor total del aspecto posterior de platillo tibial
lateral. El resto de los cartílagos femorotibiales y patelofemorales sin alteraciones.
Leve a moderado derrame articular, probablemente hemartrosis. Leve cantidad de liquido
intermuscular en la región poplítea.
Tendones cuadricipital, rotuliano, tendones de la pata de ganso, bíceps femoral y banda iliotibial
dentro de límites normales.
Impresión:
Rotura espesor y ancho total del LCA.
Rotura radial incompleta de la unión del cuerno posterior con el cuerpo del menisco lateral.
Condropatía lesiones grado 3 del compartimento femorotibial lateral, previamente descritas.
Leve a moderado derrame articular, probablemente hemartrosis
====================================================================================================
LABEL: 0
MRI of Knee with
-Locator, SG PD FatSat, SG T2W FS, SG T1W, CO T2W FS, AX T2W FS



* High signal in the soft tissue medial to the medial collateral ligament with mild increased signal intensity of proximal ligament, suspect grade 2 injury.
* Interstitial hyperintense signal of ACL, in favor of grade 1 injury.
* Bone marrow edema in bilateral femoral condyles and anteromedial and posterolateral aspect of proximal tibia, suspect bone contusion.
* Subcutaneous edema over medial aspect of right knee.
* Some joint effusion of right knee with mild hypertrophy of the synovium, indicative of synovitis.
> The contour of ACL & PCL appear to be within normal.
> No evidence of tear noted in either medial or lateral meniscus in this study.
> The quadriceps and patellar tendons appear to be within normal.

Impression:
1. Suspect grade 2 injury of MCL with adjacent soft tissue edema over anteromedial aspect of right knee.
2. Suspect grade 1 injury of ACL.
3. Bone marrow edema in distal femur and proximal tibia (major at anteromedial and posterolateral aspect), suspect bone contusion.
4. Mild synovitis of right knee joint.

Suggest correlation with clinical manifestation.

====================================================================================================
LABEL: 0
Exam Type: MRI KNEE RIGHT WO CONTRAST
Exam Date and Time: [DATE] [TIME]
Indication: Pain
Comparison: No relevant prior studies available for comparison.

TECHNIQUE:
MRI of the right knee was performed on a 3.0 Tesla system with a dedicated knee coil in three planes (axial, sagittal, and coronal), using a standard non-contrast protocol.

FINDINGS:
OSSEOUS STRUCTURES:
Alignment is anatomic. Subchondral insufficiency fracture at the medial margin of the medial tibial plateau without articular surface collapse. Background marrow signal is normal without infiltrative marrow process. No aggressive osseous lesions.

JOINT SPACE:
Small joint effusion. No intra-articular bodies. Trace Baker's cyst.

MEDIAL COMPARTMENT:
Medial meniscus: Complete radial tear of the posterior root of medial meniscus with mild extrusion.
Medial compartment cartilage: High-grade cartilage fissuring along the posterior weightbearing medial femoral condyle. Mild marginal spurring at the medial joint line.

LATERAL COMPARTMENT:
Lateral meniscus: Partial inner margin radial tear at the anterior horn/body junction of the lateral meniscus without extrusion.
Lateral compartment cartilage: Low-grade cartilage fissuring spanning the weightbearing lateral femoral condyle. High-grade cartilage fissuring along the posterior lateral tibial plateau.

PATELLOFEMORAL COMPARTMENT:
Patellofemoral compartment cartilage: Low-grade cartilage fissuring along the central trochlea. Mild cartilage thinning along the medial patellar facet with mild subchondral cystic change.

CRUCIATE LIGAMENTS:
Anterior cruciate ligament (ACL): Normal with both bundles intact.
Posterior cruciate ligament (PCL): Normal.

COLLATERAL LIGAMENTS & POSTEROLATERAL CORNER:
Medial collateral ligament (MCL): Normal.
Lateral collateral ligament (LCL) complex: Normal.
Posterolateral corner structures: Normal.

EXTENSOR MECHANISM:
Distal quadriceps tendon: No tendinosis or tear.
Patella tendon: Mild patellar tendinosis. No tendon tear.
Medial patellofemoral ligament (MPFL) and patellar retinacula: Normal.
Patellofemoral tracking: No edema in superolateral Hoffa's fat pad. No lateral patellar tilt or translation. No patella alta. Normal patellar and trochlear morphology. Normal tibial tubercle-trochlear groove (TT-TG) distance measuring 7 mm.

MUSCLES/TENDONS:
No acute muscle strain or muscle atrophy. Visualized tendons not previously discussed are intact without tendinosis or tear.

SOFT TISSUES:
Nonspecific prepatellar and scattered subcutaneous edema about the knee. No soft tissue mass. Normal popliteal neurovascular bundle.

IMPRESSION:
1.	Subchondral insufficiency fracture at the medial margin of the medial tibial plateau without articular surface collapse.
2.	Medial and lateral meniscus tears as described.
3.	Tricompartmental chondrosis.
4.	Small knee effusion.
5.	Mild patellar tendinosis without tear.
====================================================================================================
LABEL: 0
FINDINGS:

Fluid:
Small joint effusion with synovial thickening compatible with synovitis. There is popliteal cyst measuring 21 x 17 x 35 mm. Small amount of edema along the inferior margin of the popliteal cyst suggesting a minimal partial rupture.

Medial compartment (meniscus, collateral ligament, cartilage):
There is increased T2 hyperintense signal within the posterior horn of the medial meniscus extending into the posterior horn-body junction without extension to the articular surface, compatible with intrasubstance degeneration. No frank tear.

Mild thickening of the proximal fibers of the medial cruciate ligament, with mild edema, compatible with grade 1 sprain. No frank tear.

Moderate thinning of the articular cartilage of the weightbearing femur and tibia.

Lateral compartment (meniscus, collateral ligament complex, cartilage):
There is a complex degenerative tear of the lateral meniscus with partial maceration of the anterior horn and anterior body, as well as a longitudinal oblique component involving the posterior horn. There is a 4 mm small displaced fragment along the lateral tibial gutter.

Full-thickness fissures in the articular cartilage of the tibial weightbearing surface with associated subchondral bone marrow edema. There is moderate thinning of the articular cartilage of the weightbearing femur and of the tibial plateau. No subchondral bone marrow edema at the femur.

Mild increased signal intensity at the distal iliotibial band. The lateral collateral ligament complex is otherwise unremarkable.

Intercondylar compartment (anterior and posterior cruciate ligaments):
The anterior and posterior cruciate ligaments are unremarkable. Mild early intraosseous cystic changes at the tibial insertion of the anterior cruciate ligament.

Anterior compartment (extensor mechanism, cartilage, Hoffa's fat pad):
Multifocal deep and delaminating fissuring of the articular cartilage of the patellar facet without associated subchondral bone marrow edema. Additionally, there is moderate thinning of the articular cartilage of the femoral trochlea without subchondral bone marrow edema.
Mild distal quadriceps tendinosis with mild edema in the suprapatellar fat pad.
Mild patellar tendinosis.

Bones:
Normal.

Muscles and neurovascular structures:
Normal.

Other findings:
Nonspecific edema in the anterior subcutaneous tissues along the infrapatellar region.

Small amount of fluid in the pes anserine bursa.

CONCLUSION:

- Tricompartmental moderate chondral thinning with deep fissures at the lateral and patellofemoral compartments, as described above.
- Complex degenerative tear of the lateral meniscus with tiny displaced fragment.
- Low-grade sprain of the medial collateral ligament.
- Small joint effusion with synovitis.
- Moderate-sized popliteal cyst with minimal partial rupture.

====================================================================================================
LABEL: 0
Técnica: RMN de la rodilla. Resultados: Fricción de la banda iliotibial. Síndrome de pinzamiento de la almohadilla grasa de Hoffa. Condropatía rotuliana. Impresión: Fricción de la banda iliotibial. Síndrome de pinzamiento de la almohadilla grasa de Hoffa. Condropatía rotuliana.
====================================================================================================
LABEL: 1
Técnica: RMN de la rodilla. Resultados: Rotura del LCA. Rotura parcial del LCM. Rotura de menisco interno y lateral. Derrame. Contusiones óseas femorotibiales. Impresión: Rotura del LCA. Rotura parcial del LCM. Rotura de menisco interno y lateral. Derrame. Contusiones óseas femorotibiales.
====================================================================================================
LABEL: 1
In the medial compartment, the meniscus is not torn and there is no focal chondrosis or chondral injury.
 The lateral compartment, there is longitudinal vertical oblique tear at the posterior horn of the lateral meniscus. There is no focal chondrosis or chondral injury.
 The patellofemoral joint, the patellar and trochlear cartilage appears congruent without chondral lesion. The medial patellofemoral ligament is intact.
 In the intercondylar notch, there is complete tear of the anterior cruciate ligament, at mid substance. The posterior cruciate ligament is intact.
 There is grade II ligamentous sprain (partial tear) of the medial collateral ligament. The posteromedial oblique ligament is intact. The lateral collateral ligament complexes are intact. The extensor mechanism is normal.

In [69]:
# Hesabatlardakı ümumi strukturu və əsas terminlərin paylanmasını yoxlayırıq
reports = train_dataset['Report'].dropna()
print(f'Ümumi hesabat sayı: {len(reports)}')
print(f'Unikal hesabat sayı: {reports.nunique()}')

# Məsələn, "intact" və "tear" sözlərinin keçmə tezliyi
intact_count = reports.str.contains('intact|normal|preserved', case=False).sum()
tear_count = reports.str.contains('tear|rupture|rotura|ρήξη', case=False).sum()

print(f'"Intact/Normal" keçən hesabat sayı: {intact_count}')
print(f'"Tear/Rupture" keçən hesabat sayı: {tear_count}')

Ümumi hesabat sayı: 4407
Unikal hesabat sayı: 4276
"Intact/Normal" keçən hesabat sayı: 2753
"Tear/Rupture" keçən hesabat sayı: 2500

In [70]:
# Hər bir hədəf sütunu üzrə positive (1) və negative (0) saylarını yoxlayırıq
target_columns = [
    'ACL',
    'MCL',
    'Medial Meniscus',
    'Lateral Meniscus',
    'Medial OA',
    'Lateral OA',
    'PF OA',
    'Effusion',
    'Synovitis',
    "Baker's",
    'Contusion',
    'Fracture',
]
label_counts = train_dataset[target_columns].sum()
print("Hər hədəf üzrə müsbət (1) halların sayı:")
print(label_counts)

Hər hədəf üzrə müsbət (1) halların sayı:
ACL                 24.0
MCL                  9.0
Medial Meniscus     26.0
Lateral Meniscus    23.0
Medial OA           15.0
Lateral OA          11.0
PF OA               21.0
Effusion            35.0
Synovitis           27.0
Baker's             12.0
Contusion           19.0
Fracture            18.0
dtype: float64

In [71]:

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import f1_score, roc_auc_score
from sklearn.pipeline import Pipeline



# 1(Keywords)

keywords_expanded = {
    'ACL': [
        'acl',
        'anterior cruciate',
        'vorderes kreuzband',
        'cruzado anterior',
        'ön çapraz',
        'kreuzband',
        'anterior cruciate ligament',
        'vkb',
        'lkd',
        'lca',
        'χιαστός',
    ],
    'MCL': [
        'mcl',
        'medial collateral',
        'innenband',
        'colateral medial',
        'iç yan',
        'medial collateral ligament',
        'lcm',
        'medial kollateral',
        'mcm',
    ],
    'Medial Meniscus': [
        'medial meniscus',
        'menisco medial',
        'innenmeniskus',
        'medyal menisküs',
        'medial menisküs',
        'posterior horn medial meniscus',
        'meniscal tear medial',
        'menisco interno',
        'έσω μηνίσκος',
        'iç menisküs',
    ],
    'Lateral Meniscus': [
        'lateral meniscus',
        'menisco lateral',
        'außenmeniskus',
        'lateral menisküs',
        'anterior horn lateral meniscus',
        'menisco externo',
        'έξω μηνίσκος',
        'dış menisküs',
    ],
    'Medial OA': [
        'medial oa',
        'medial osteoarthritis',
        'artrosis medial',
        'femorotibial medial',
        'chondrosis medial',
        'medial compartment degeneration',
        'gonavartrose medial',
        'gonartrose',
        'medial tibiofemoral compartment',
        'medial compartment chondrosis',
        'medial joint space',
        'chondromalacia medial',
        'cartilage loss medial',
        'έσω',
        'χόνδρου',
        'medial tibial plateau',
        'subchondral',
        'osteophyte',
        'osteofytose',
        'kraakbeenverlies',
        'medial femorotibial',
        'medial kompartment',
    ],
    'Lateral OA': [
        'lateral oa',
        'lateral osteoarthritis',
        'artrosis lateral',
        'femorotibial lateral',
        'chondrosis lateral',
        'lateral compartment degeneration',
        'lateraal',
        'lateral femorotibiaal',
        'laterale tibiaplateau',
        'lateral compartment chondrosis',
        'kraakbeenlijden lateraal',
        'lateral joint space narrowing',
        'lateral kompartment',
    ],
    'PF OA': [
        'pf oa',
        'patellofemoral',
        'retropatellar',
        'chondromalacia patellae',
        'patella',
        'trochlea',
        'condropatía rotuliana',
        'condropatia rotuliana',
        'úlcera condral',
        'femoropatelar',
        'artrosis femoropatelar',
        'patellofemoral chondropathy',
        'kondromalazi',
        'troklear',
    ],
    'Effusion': [
        'effusion',
        'derrame',
        'erguss',
        'fluid',
        'líquido',
        'sıvı',
        'gelenkflüssigkeit',
        'joint effusion',
        'hydrops',
        'efüzyon',
        'izlıv',
        'su toplama',
        'fluid collection',
        'fluid accumulation',
        'joint fluid',
        'liquid collection',
        'synovial fluid',
    ],
    'Synovitis': [
        'synovitis',
        'sinovitis',
        'synovial',
        'synoviale',
        'sinovit',
        'synovial thickening',
        'reizsynovialitis',
        'synovial proliferation',
        'synovial membrane thickening',
        'hypertrophy of the synovium',
        'reizsinoviyalitis',
        'synovial hypertrophy',
    ],
    "Baker's": [
        'baker',
        'popliteal cyst',
        'quiste poplíteo',
        'bechter',
        'popliteal',
        'baker kisti',
        'baker cisti',
        'popliteal bursa',
    ],
    'Contusion': [
        'contusion',
        'contusión',
        'bone bruise',
        'ödemsignal',
        'ödem',
        'marrow edema',
        'bone marrow',
        'kontüzyon',
        'koştani edem',
        'botoedeem',
        'kemik iliği ödemi',
    ],
    'Fracture': [
        'fracture',
        'fractura',
        'fraktur',
        'kırık',
        'osseous defect',
        'bone fracture',
        'fraktür',
        'impactiefractuur',
        'subchondral fracture',
        'avulsion',
    ],
}

target_columns = list(keywords_expanded.keys())


# 2. Rule-Based Engine V2
def advanced_sentence_predict_v2(report):
  if pd.isna(report):
    return {col: 0 for col in target_columns}

  sentences = str(report).split('.')
  preds = {}

  for col in target_columns:
    col_matched = 0
    kws = keywords_expanded[col]

    for sentence in sentences:
      sent_lower = sentence.lower()
      if any(kw in sent_lower for kw in kws):
        if col in ['Effusion', 'Synovitis', "Baker's"]:
          has_negation = any(
              neg in sent_lower
              for neg in [
                  'no ',
                  'without ',
                  'free of',
                  'absent',
                  'not seen',
                  'no evidence',
              ]
          )
          if not has_negation:
            col_matched = 1
            break
        else:
      
          is_intact = any(
              neg in sent_lower
              for neg in ['intact', 'normal', 'preserved', 'within normal']
          )
          is_torn = any(
              pos in sent_lower
              for pos in [
                  'tear',
                  'rupture',
                  'lesion',
                  'fracture',
                  'edema',
                  'sprain',
                  'defect',
                  'degenerative',
              ]
          )

          if is_torn and not is_intact:
            col_matched = 1
            break
          elif is_intact and not is_torn:
            col_matched = 0
            break

    preds[col] = col_matched
  return preds


print('Rule-based engine is ready')


# 3. training process HyBRiD MODEL(TF-IDF + ML)

def train_hybrid_models(train_df):
  labeled_mask = train_df['ACL'].notna()
  df_gold = train_df[labeled_mask].copy()
  X_train = df_gold['Report'].astype(str)

  ml_models = {}
  print('ML modelləri öyrədilir...')

  for col in target_columns:
    y_train = df_gold[col].values.astype(int)
    if len(np.unique(y_train)) < 2:
      continue

    pipeline = Pipeline([
        (
            'tfidf',
            TfidfVectorizer(
                ngram_range=(1, 2), max_features=1000, stop_words='english'
            ),
        ),
        ('clf', LogisticRegression(class_weight='balanced', max_iter=1000)),
    ])
    pipeline.fit(X_train, y_train)
    ml_models[col] = pipeline

  print('TF-IDF nd Logistic Regression ')
  return ml_models, df_gold


# 4.hybrid predictor and ensemble

def create_hybrid_predictor(ml_models):
  def hybrid_predict(report):
    rule_preds = advanced_sentence_predict_v2(report)

    ml_preds = {}
    for col in target_columns:
      if col in ml_models:
        pred = ml_models[col].predict([str(report)])[0]
        ml_preds[col] = int(pred)
      else:
        ml_preds[col] = 0

    # Logical OR Ensemble 
    final_preds = {}
    for col in target_columns:
      r_val = rule_preds.get(col, 0)
      m_val = ml_preds.get(col, 0)
      final_preds[col] = 1 if (r_val == 1 or m_val == 1) else 0

    return final_preds

  return hybrid_predict


# 5.PIPELINE EXECUTION

ml_models, df_gold = train_hybrid_models(train_dataset)
predict_func = create_hybrid_predictor(ml_models)


all_predictions = []
for rep in train_dataset['Report']:
  preds = predict_func(rep)
  all_predictions.append(preds)

df_submission = pd.DataFrame(all_predictions)
if 'Id' in train_dataset.columns:
  df_submission.insert(0, 'Id', train_dataset['Id'])

df_submission.to_csv('submission.csv', index=False)
print('"submission.csv" file is ready.')
display(df_submission.head())

Rule-based engine is ready
ML modelləri öyrədilir...
TF-IDF nd Logistic Regression
"submission.csv" file is ready.

,ACL,MCL,Medial Meniscus,Lateral Meniscus,Medial OA,Lateral OA,PF OA,Effusion,Synovitis,Baker's,Contusion,Fracture
0,0,1,0,0,0,0,1,1,1,0,0,0
1,1,0,0,0,0,0,1,1,1,0,0,0
2,0,0,0,1,0,1,1,0,0,0,0,0
3,1,0,1,1,0,0,1,0,0,1,1,1
4,0,0,0,0,0,0,0,0,0,1,0,1

In [75]:
sample_subm=pd.read_csv("C:/Users/sevinj.rahimova/Desktop/Kaggle competition/RSNA Knee Abnormality Detection/sample_submission.csv")

In [76]:
sample_subm

,StudyInstanceUID,ACL,MCL,Medial Meniscus,Lateral Meniscus,Medial OA,Lateral OA,PF OA,Effusion,Synovitis,Baker's,Contusion,Fracture
0,1.2.826.0.1.3680043.8.498.10047035057544427318...,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5
1,1.2.826.0.1.3680043.8.498.10062861783145312629...,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5
2,1.2.826.0.1.3680043.8.498.10067514707072572280...,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5